package mime

// MIME represents Internet Media Types as defined by IANA.
// Reference: https://www.iana.org/assignments/media-types/media-types.xhtml
type MIME string

func (m MIME) String() (method string) {
	return string(m)
}

const (
	AACAudio                 MIME = "audio/aac"
	AVIFImage                MIME = "image/avif"
	AVIVideo                 MIME = "video/x-msvideo"
	AbiWordDocument          MIME = "application/x-abiword"
	AmazonKindleEBook        MIME = "application/vnd.amazon.ebook"
	AppleInstallerPackage    MIME = "application/vnd.apple.installer+xml"
	ArchiveDocument          MIME = "application/x-freearc"
	BZip2Archive             MIME = "application/x-bzip2"
	BZipArchive              MIME = "application/x-bzip"
	BinaryData               MIME = "application/octet-stream"
	BitmapImage              MIME = "image/bmp"
	BourneShellScript        MIME = "application/x-sh"
	CDAudio                  MIME = "application/x-cdf"
	CSS                      MIME = "text/css"
	CSV                      MIME = "text/csv"
	CShellScript             MIME = "application/x-csh"
	EPUB                     MIME = "application/epub+zip"
	GIF                      MIME = "image/gif"
	GZipCompressedArchive    MIME = "application/gzip"
	HTML                     MIME = "text/html"
	ICalendar                MIME = "text/calendar"
	IconFormat               MIME = "image/vnd.microsoft.icon"
	JPEG                     MIME = "image/jpeg"
	JSON                     MIME = "application/json"
	JSONLD                   MIME = "application/ld+json"
	JavaArchive              MIME = "application/java-archive"
	JavaScript               MIME = "text/javascript"
	JavaScriptModule         MIME = "text/javascript"
	MIDI                     MIME = "audio/midi"
	MP3Audio                 MIME = "audio/mpeg"
	MP4Video                 MIME = "video/mp4"
	MPEGTransportStream      MIME = "video/mp2t"
	MPEGVideo                MIME = "video/mpeg"
	MSEmbeddedOpenTypeFonts  MIME = "application/vnd.ms-fontobject"
	MSExcel                  MIME = "application/vnd.ms-excel"
	MSExcelOpenXML           MIME = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
	MSPowerPoint             MIME = "application/vnd.ms-powerpoint"
	MSPowerPointOpenXML      MIME = "application/vnd.openxmlformats-officedocument.presentationml.presentation"
	MSVisio                  MIME = "application/vnd.visio"
	MSWord                   MIME = "application/msword"
	MSWordOpenXML            MIME = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
	OGG                      MIME = "application/ogg"
	OGGAudio                 MIME = "audio/ogg"
	OGGVideo                 MIME = "video/ogg"
	OpenDocumentPresentation MIME = "application/vnd.oasis.opendocument.presentation"
	OpenDocumentSpreadsheet  MIME = "application/vnd.oasis.opendocument.spreadsheet"
	OpenDocumentText         MIME = "application/vnd.oasis.opendocument.text"
	OpenTypeFont             MIME = "font/otf"
	OpusAudio                MIME = "audio/opus"
	PDF                      MIME = "application/pdf"
	PHP                      MIME = "application/x-httpd-php"
	PNG                      MIME = "image/png"
	RARArchive               MIME = "application/vnd.rar"
	RichTextFormat           MIME = "application/rtf"
	SVG                      MIME = "image/svg+xml"
	SevenZipArchive          MIME = "application/x-7z-compressed"
	TARArchive               MIME = "application/x-tar"
	TIFF                     MIME = "image/tiff"
	Text                     MIME = "text/plain"
	ThreeG2AudioVideo        MIME = "video/3gpp2"
	ThreeGPAudioVideo        MIME = "video/3gpp"
	TrueTypeFont             MIME = "font/ttf"
	WAVAudio                 MIME = "audio/wav"
	WEBMAudio                MIME = "audio/webm"
	WEBMVideo                MIME = "video/webm"
	WEBPImage                MIME = "image/webp"
	WOFF                     MIME = "font/woff"
	WOFF2                    MIME = "font/woff2"
	XHTML                    MIME = "application/xhtml+xml"
	XML                      MIME = "application/xml"
	XUL                      MIME = "application/vnd.mozilla.xul+xml"
	ZIPArchive               MIME = "application/zip"
)
